# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - frontend-tfg

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: create-firebase-json-src
      id: create-firebase-json-src
      uses: jsdaniell/create-json@1.1.2
      with:
        name: "firebase-credentials.json"
        json: ${{ secrets.FIREBASE_CREDENTIALS_FRONTEND_JSON }}
        dir: 'frontend/src/'

    - name: create-firebase-json-public
      id: create-firebase-json-public
      uses: jsdaniell/create-json@1.1.2
      with:
        name: "firebase-credentials.json"
        json: ${{ secrets.FIREBASE_CREDENTIALS_FRONTEND_JSON }}
        dir: 'frontend/public/'

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: npm install
      run: |
        cd frontend
        npm install
        npm run build

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'frontend-tfg'
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_CREDENTIALS_FRONTEND }}
        package: ./frontend
