# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - backend-tfg

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: create-firebase-json
      id: create-firebase-json
      uses: jsdaniell/create-json@1.1.2
      with:
        name: "firebaseServiceAccount.json"
        json: ${{ secrets.FIREBASE_CREDENTIALS_JSON }}
        dir: 'backend/'

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: npm install
      run: |
        cd backend
        npm install

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'backend-tfg'
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_CREDENTIALS_BACKEND }}
        package: ./backend
